classmanager:
  upload:
    dir: data0/uploads/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wx?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    #连接池的配置信息
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: 127.0.0.1
    port: 6379
    #password: MiPP0int2o17
    password:
    pool:
      max-active: 30
      max-idle: 10
      max-wait: 10000
    timeout: 0
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
